# Generated by Django 6.0.1 on 2026-01-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('company_code', models.CharField(blank=True, max_length=50, verbose_name='Įmonės kodas')),
                ('vat_code', models.CharField(blank=True, max_length=50, verbose_name='PVM kodas')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='El. paštas')),
                ('address', models.TextField(blank=True, verbose_name='Adresas')),
                ('active', models.BooleanField(default=True, verbose_name='Aktyvus')),
            ],
        ),
    ]
