# Generated by Django 6.0.1 on 2026-01-25 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mėnesinis abonementas (€)')),
                ('hosting_yearly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hostingo kaina metams (€)')),
                ('hosting_valid_until', models.DateField(verbose_name='Hostingo apmokėjimas galioja iki')),
                ('active', models.BooleanField(default=True, verbose_name='Aktyvus')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='billing.client', verbose_name='Klientas')),
            ],
        ),
    ]
