# Generated by Django 6.0.1 on 2026-01-25 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='El. paštas')),
                ('email_type', models.CharField(choices=[('accounting', 'Buhalterija'), ('administration', 'Administracija'), ('other', 'Kita')], default='other', max_length=50, verbose_name='Tipas')),
                ('active', models.BooleanField(default=True, verbose_name='Aktyvus')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='billing.client', verbose_name='Klientas')),
            ],
        ),
    ]
