# Generated by Django 6.0.1 on 2026-01-25 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_clientemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.CharField(max_length=255, verbose_name='Darbo aprašymas')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Kiekis / valandos')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kaina už vienetą (€)')),
                ('billed', models.BooleanField(default=False, verbose_name='Įtraukta į sąskaitą')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='billing.client', verbose_name='Klientas')),
            ],
        ),
    ]
