# Generated by Django 6.0.1 on 2026-01-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_worklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Numeris')),
                ('invoice_type', models.CharField(choices=[('monthly', 'Mėnesinė'), ('hosting', 'Hostingo avansinė')], max_length=20, verbose_name='Tipas')),
                ('period_from', models.DateField(verbose_name='Periodas nuo')),
                ('period_to', models.DateField(verbose_name='Periodas iki')),
                ('issued_date', models.DateField(verbose_name='Išrašymo data')),
                ('due_date', models.DateField(verbose_name='Apmokėti iki')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Suma (€)')),
                ('paid', models.BooleanField(default=False, verbose_name='Apmokėta')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.client')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Aprašymas')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Kiekis')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kaina (€)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Suma (€)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
            ],
        ),
    ]
