# Generated by Django 6.0.1 on 2026-01-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_invoiceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='PDF'),
        ),
    ]
