# Generated by Django 6.0.1 on 2026-01-26 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='title',
            field=models.CharField(default='Abonentas', max_length=255, verbose_name='Už ką (pavadinimas)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='billing.client', verbose_name='Klientas'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='hosting_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Hostingo apmokėjimas galioja iki'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='hosting_yearly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hostingo kaina metams (€)'),
        ),
    ]
