# Generated by Django 6.0.1 on 2026-01-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_subscription_title_alter_subscription_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="net_amount",
            field=models.DecimalField(
                default=0,
                max_digits=12,
                decimal_places=2,
                verbose_name="Suma be PVM",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vat_rate",
            field=models.DecimalField(
                default=0.21,
                max_digits=4,
                decimal_places=2,
                verbose_name="PVM tarifas",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vat_amount",
            field=models.DecimalField(
                default=0,
                max_digits=12,
                decimal_places=2,
                verbose_name="PVM suma",
            ),
        ),
    ]
